### ISSUE TITLE
AMR-to-text generation

### ISSUE THREAD

**Issue by anspas** [chriott/amr-summarizer#5]
with SPRING module (https://amrlib.readthedocs.io/en/latest/api_model/#graph-to-sequence-functions-generation)

**Comment by anspas** [comment]
To Do: How does the AMR-to-text generator deal with tense? Is there an option for adding tense information? (generator: “unable to add tense information to graph”)

**Comment by chriott** [comment]
> https://amrlib.readthedocs.io/en/latest/models/#generate-t5wtense
> **Additional generate parameters:**
> use_tense : Whether or not to add tense tags to the graph, prior to generation (default is True). Note that the metadata tag snt for the original sentence, must be present for annotation.
